travis:
  secure:
    BINSTAR_TOKEN: a13O0ietUohb0tFBNpjDZ0/xdyqdAY5TzvwxHHZnH6ZhaJr+rguG9rDkzcMp7xv7RZpPtwc1eiXEGqxmbuYteyT38oug3fEHbV7ovAYWIFOj/yNrIcFQKoAbF2o+1RLPGwJCXt34oYAYh88JMg4dcqejk8Ny0s2UuWuQSXhBQYNm/xTik83Zs7JdH+oKh1oHjIppzXn+lVPempO/PmQtXx2NcerzYRc713+gYDPq03zeQ9HnjZ4rZ+pe8TiW+qlojFV5jTYmXRIGLGOTH5HPv3U3xTc8tQw2IAV4Wa1nsZo5PXFesDHeg2mSyAY365mXdb0n9BgJKp2zTafDjVdqw0VnqbTJ8f4IlN+aJjKRR9hseD9e//+nb7Qag+tqkJKQ7Fv5z0JFvfV3SJaRbKFM1kQePLxULQh1Ygyn68VhJ4eMmckMP1hH/rXVRdaUAyc3Bz3+Fwk5GXQXysGSXl9H8VzfDtlNZXP0yQGxxogabMomM7nUQdULRLqyoBTG78Cx4wW0tCQ11PfHB14lrj951rkcnqELgloiiqDTvgMB5G3Nl9TZZgevyyHjS41fxY2WEOAQtl/sWb14DPYOWnFYYZs+5BFco2dbLLk/d0x5BtG/4VVL2d2fGedm3eu3v4D//0RdeltLq10qN9qXnEoOvnk5EDBD9iEc+CR6AQPwXrE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
